apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
    name: configmap-volume
spec:
  containers:
  - name: test
    image: busybox:1.28
    command: [ "sh", "-c", "echo 'The app is running!' && tail -f /dev/null" ]
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
  volumes:
  - name: config-vol
    configMap:
      name: log-config
      items:
      - key: log_level
        path: log_level.conf
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          # ports:
          # - containerPort: <Port>
