apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-demo
  labels:
    app: myapp
spec:
  containers:
  - name: my-container
    image: busybox
    command: [ "/bin/sh", "-c", "cat /etc/podinfo/*; sleep 3600" ]
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    - name: resources
      mountPath: /etc/resources
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "pod_name"
        fieldRef:
          fieldPath: metadata.name
      - path: "namespace"
        fieldRef:
          fieldPath: metadata.namespace
  - name: resources
    downwardAPI:
      items:
      - path: "cpu_limit"
        resourceFieldRef:
          containerName: my-container
          resource: limits.cpu
      - path: "memory_limit"
        resourceFieldRef:
          containerName: my-container
          resource: limits.memory
