apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: myapp
        image: mysql:8.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      # livenessProbe:
      #   initialDelaSeconds: 10
      #   periodSeconds: 5
      # readinessProbe:
      #   initialDelaSeconds: 5
      #   periodSeconds: 5
