# Example Liveness Probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-deployment
  labels:
    env: test
    app: liveness-example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: liveness-selector
  template:
    metadata:
      labels:
        name: liveness-selector
    spec:
      containers:
      - name: liveness-prob-container
        image: nginx
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3 # ensures that the probe waits 3 seconds before running.
          periodSeconds: 5 # checks the liveness every 5 seconds.

# Kubernetes sends an HTTP request to http://<pod-ip>:80/health.

# If the response is not 200 OK, Kubernetes restarts the container.
