# Startup Probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-probe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: startup-selector
  template:
    metadata:
      labels:
        app: startup-selector
    spec:
      containers:
      - name: startup-selector
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
