apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-0
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/~/data/mongodb-0"
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  #mountOptions:
  #- hard
  #- nfsvers=4.1
  #nfs:
  #  path: /tmp
  #  server: 172.17.0.2
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-1
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/~/data/mongodb-1"
  persistentVolumeReclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-2
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/~/data/mongodb-2"
  persistentVolumeReclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-3
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/~/data/mongodb-3"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-4
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/~/data/mongodb-4"
  persistentVolumeReclaimPolicy: Retain
