apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None #This make it headless service
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
