apiVersion: v1
kind: Job
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: alpine:latest
      command: [ 'sh', '-c', 'echo "logging" > /opt/logs.txt' ]
      volumeMounts:
      - name: data
        mountPath: /opt
      initContainers:
      - name: logshipper
        image: alpine:latest
        restartPolicy: Always
        command: [ 'sh', '-c', 'tail -F /opt/logs.txt' ]
        volumeMounts:
        - name: data
          mountPath: /opt
      restartPolicy: Never
      volumes:
      - name: data
        emptyDir: {}
