apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-nodeport
  name: svc-nodeport
spec:
  ports:
  - name: 80-80
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: svc-nodeport
  type: NodePort
status:
  loadBalancer: {}
