apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-01-10T01:23:51Z"
  labels:
    app: svc-loadbalancer
  name: svc-loadbalancer
  namespace: default
  resourceVersion: "336742"
  uid: 7e094c21-dbdf-4a0b-8e4b-4f28b3fa08cc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.94.186
  clusterIPs:
  - 10.96.94.186
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    nodePort: 32032
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: svc-loadbalancer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
