apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    env: test
    class: service
    type: frontend
    kind: Service
spec:
  type: ClusterIP     # Specifies the service type i.e ClusterIP or NodePort
  selector:
    kind: Deployment   # Apply this service to any pods which has the specific label
  ports:
  - port: 80     #Containers port exposed
    targetPort: 80   # Pods port
  
