apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: multinode
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30010
    hostPort: 30010
    protocol: TCP
- role: worker
- role: worker
- role: worker

