apiVersion: v1
kind: Pod
metadata: 
  name: quota-mem-cpu-demu
  namespace: quota-mem-cpu-example
spec:
  containers:
    - name: quota-mem-cpu-demo-ctr
      image:  nginx
      resources:
        requests:
          cpu: "400m"
          memory: "600Mi"
        limits:
          cpu: "800m"
          memory: "800Mi"

