apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
  namespace: quota-mem-cpu-example
spec:
  containers:
    - name: quota-mem-cpu-demo-2-ctr
      image: nginx
      resources:
        requests:
          cpu: "400m"
          memory: "700Mi"
        limits:
          cpu: "800m"
          memory: "1Gi"
