apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
  labels:
    class: service
    env: test
    tier: frontend
spec:
  type: NodePort
  selector:
    kind: Deployment
    app: nginx
    env: test
  ports:
  # Optional field
  # By default and for convenience, the Kubernetes control plane
  # will allocate a port from a range (default: 30000-32767)
  - nodePort: 30010
    port: 80
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 80
    
