# multi-container Pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-containe
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "128m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx

  - name: log-sidecar
    image: busybox:latest
    command: [ "sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 5; done;" ]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  volumes:
  - name: log-volume
    emptyDir: {}
