apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
  labels:
    kind: pod
    env: test
    tier: backend
spec:
  containers:
  - name: c01
    image: centos
    command: ["/bin/bash", "-c", "sleep 150000"]
    volumeMounts:             # Mount definition inside the container
    - mountPath: /tmp/cache
      name: cache-volume
  - name: c02
    image: centos
    command: ["/bin/bash", "-c", "sleep 150000"]
    volumeMounts:
    - mountPath: /tmp/cache  
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
     sizeLimit: "500Mi"
     medium: Memory
    
