apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: namespace-dev-deploy
  name: namespace-dev-deploy
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: namespace-dev-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: namespace-dev-deploy
    spec:
      containers:
      - image: registry.k8s.io/serve_hostname
        name: serve-hostname-8vbtk
        resources: {}
status: {}
