apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
  labels:
    env: test
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do echo "Running...."; sleep 3600; done
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh", "-c", "echo Hello from postStart handler> /tmp/poststart.log" ]
      preStop:
        exec:
          command: [ "/bin/sh", "-c", "echo Goodbye from the preStop handler >/tmp/preStop.log" ]
