apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
  labels:
    class: Pod
    env: test
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "mkdir -p /tmp/hostpath-data"]
    volumeMounts:
    - name: myhostpath
      mountPath: /tmp/hostpath-data
  containers:
  - name: hostpath-volume-container
    image: centos
    command: ["/bin/bash", "-c", "sleep 20000"]
    volumeMounts:
    - name: myhostpath
      mountPath: /tmp/hostpath
  volumes:
  - name: myhostpath
    hostPath:
      path: /tmp/hostpath-data
      type: DirectoryOrCreate
