apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: service-without-selector-1
    # by convention, use the name of the Service
    # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: service-without-selector
addressType: IPV4
ports:
- name: http # should match with the name of the service port defined in 'service-without-selector'
  appProtocol: TCP
  protocol: TCP
  port: 9376
endPoints:
- addresses:
  - "10.4.5.6"
- addresses:
  - "10.1.2.3"
