apiVersion: v1
kind: Service
metadata:
  name: Frontend-NodePort-Service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 8080
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)
    nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: Backend-NodePort-Service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007 # ❌ Conflict!, already occupied by frontend NodePort Service, so we can use any port between 30000 to 32767 except 30007 to avoid collision.
