   # This is a Deployment yaml file that will manage a ReplicaSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: deploy-container
        image: nginx
        ports:
        - containerPort: 80

