# This is multi container pod
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    env: demo
    type: frontend
spec: 
  containers:
  - name: nginx-container2
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-container3
    image: nginx
    ports:
    - containerPort: 8080
