apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"quota-mem-cpu-demo","namespace":"quota-mem-cpu-example"},"spec":{"containers":[{"image":"nginx","name":"quota-mem-cpu-demo-ctr","resources":{"limits":{"cpu":"800m","memory":"800Mi"},"requests":{"cpu":"400m","memory":"600Mi"}}}]}}
  name: quota-mem-cpu-demo
  namespace: quota-mem-cpu-example
spec:
  containers:
  - image: nginx
    name: quota-mem-cpu-demo-ctr
    resources:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 400m
        memory: 600Mi
