#This is cronjob yaml which execute at specified minute(0-59),hour(0-23),day of the month(1-31),month(1-12), day of the week(0-6)
# * * * * *
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c']
            args: ['date; echo Hello from the Kubernetes cluster']
          restartPolicy: OnFailure

