apiVersion: v1
kind: Pod
metadata: 
  name: mem-demo-3
  namespace: memory-example
spec:
  containers:
  - name: memory-demo-container3
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "550M", "--vm-hang", "1"]  

