# This is the nodePort yaml file which used to expose our front end app throgh service.
# Port used between 30001 to 32767
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    # By default and for convenience, the `targetPort` is set to
    # the same value as the `port` field.
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)
  selector:
    env: demo

