apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-downwardapi-volume-example
  labels:
    zone: us-east-1
    cluster: multi-node-cluster2
  annotations:
    build: two
    builder: Rajeev-Singh
spec:
  containers:
  - name: client-container
    image: registry.k8s.io/busybox:1.27.2
    command: [ "sh", "-c" ]
    args:
    - while true; do if [[ -e /etc/podinfo/labels ]]; then echo -en '\n\n'; cat /etc/podinfo/labels; fi; if [[ -e /etc/podinfo/annotations]]; then echo -en '\n\n'; cat /etc/podinfo/annotations; fi; sleep 5; done;

    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
